#!/bin/bash

## This file has been generated by tools/setupbuilder.py

###########################################
##                setup.sh               ##
##   A dotfile installer for ArchLinux   ##
##                                       ##
##                 GGORG                 ##
##      https://gh.ggorg.tk/dotfiles     ##
##          shells/zsh/setup.sh          ##
###########################################
echo -e "\e[1;33mZSH \e[1;32mdotfiles setup \e[4;33mfor ArchLinux\e[0m"
echo -e "\e[1;32m[*] Installing packages...\e[0m"

sudo pacman -Sy --needed --noconfirm bat bat-extras curl diffutils exa fzf git grep iproute2 ipython ncurses neovim nmap pkgfile python python-pip ripgrep starship sudo ttf-font-nerd xclip zoxide zsh zsh-autosuggestions zsh-syntax-highlighting || exit 1

if ! hash paru 2>/dev/null; then
    echo -e "\e[1;32m[*] Installing \e[1;33mparu \e[1;32m[*]AUR helper...\e[0m"
    git clone https://aur.archlinux.org/paru-bin.git
    cd paru-bin
    makepkg -si
    cd ..
    rm -rf paru-bin
fi

echo -e "\e[1;32m[*] Installing AUR packages...\e[0m"
paru -S --needed --noconfirm paru paruz zsh-you-should-use || exit 1

echo -e "\e[1;32m[*] Backing up your existing dotfiles...\e[0m"

echo -e "\e[0;33m - $HOME/.aliasrc...\e[0m"
mv "$HOME/.aliasrc" "$HOME/.aliasrc.bak"

echo -e "\e[0;33m - $HOME/.zshrc...\e[0m"
mv "$HOME/.zshrc" "$HOME/.zshrc.bak"


echo -e "\e[1;32m[*] Symlinking the dotfiles...\e[0m"

echo -e "\e[0;33m - aliasrc...\e[0m"
ln -s "$PWD/aliasrc" "$HOME/.aliasrc"

echo -e "\e[0;33m - zshrc...\e[0m"
ln -s "$PWD/zshrc" "$HOME/.zshrc"

echo -e '\e[1;33m[!] Do \e[4mnot\e[0m\e[1;33m remove or move this repo or your dotfiles will break!\e[0m'

echo -e "\e[1;32m[*] Installing dependencies...\e[0m"
oldpwd=$PWD
cd ../../
echo -e "\e[0;33m - shells/starship-prompt...\e[0m"
cd shells/starship-prompt
bash setup.sh
cd ../../
cd $oldpwd

echo "$PWD" > "$HOME/.dotfiles_setup_path"
touch .installed
