#!/usr/bin/zsh
# @File shells/zsh/zshrc
# @Copy ~/.zshrc

#########################################
##               ~/.zshrc              ##
##   The main ZSH configuration file   ##
##                                     ##
##                GGORG                ##
##     https://gh.ggorg.tk/dotfiles    ##
##           shells/zsh/zshrc          ##
#########################################

## If not running interactively, don't do anything
[[ $- != *i* ]] && return

### EXPORTS ###

## @Change your editor here
export EDITOR='nvim'
export VISUAL="$EDITOR"

## Sudo prompt
export SUDO_PROMPT="[sudo]  %p's password: "

### HISTORY SETTINGS ###

## Set the history file to ~/.zsh_history
HISTFILE=~/.zsh_history

## Set the shell history size to 1000
HISTSIZE=1000

## Set the file history size to 10000
SAVEHIST=10000

## Basically ignore duplicates
setopt hist_expire_dups_first
setopt hist_ignore_dups

### SHELL OPTIONS ###

## CD into a directory by just typing its name
setopt autocd

## Notify that a backround command has finished
setopt notify

## @Uncomment to hide EOL sign ('%')
#PROMPT_EOL_MARK=""

## Allow comments in interactive mode
setopt interactivecomments

## Enable filename expansion for property (a=b) arguments (used in dd)
setopt magicequalsubst

### KEYBINDINGS ###

## Use Vim keys
## @Comment to use normal (Emacs) keys
bindkey -v

## Exit ZSH
function exit_zsh() { exit; }
zle -N exit_zsh
bindkey '^D' exit_zsh

## Clear the entire backbuffer
function clear-screen-and-scrollback() {
  echoti civis >"$TTY"
  printf '%b' '\e[H\e[2J' >"$TTY"
  zle .reset-prompt
  zle -R
  printf '%b' '\e[3J' >"$TTY"
  echoti cnorm >"$TTY"
}
zle -N clear-screen-and-scrollback
bindkey '^L' clear-screen-and-scrollback

### COMPLETION OPTIONS ###

zstyle :compinstall filename '/home/ggorg/.zshrc'
autoload -Uz compinit
compinit

### COMMON $PATH DIRECTORIES ###

## ~/.bin
if [ -d "$HOME/.bin" ]; then
  PATH="$HOME/.bin:$PATH"
fi

## ~/.local/bin
if [ -d "$HOME/.local/bin" ]; then
  PATH="$HOME/.local/bin:$PATH"
fi

## ~/Applications (a common AppImage directory)
if [ -d "$HOME/Applications" ]; then
  PATH="$HOME/Applications:$PATH"
fi

### TERMINAL TITLE ###

case ${TERM} in
xterm* | rxvt* | Eterm* | aterm | kterm | gnome* | alacritty | st | konsole* | kitty*)
  PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
  ;;
*) ;;

esac

### COLORED COMMANDS ###

## ls
alias ls="ls --color=auto"

## grep
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

## diff
alias diff="diff --color=auto"

## ip
alias ip="ip --color=auto"

### CONFIG FILES ###

## Aliases
if [ -f "$HOME/.aliasrc" ]; then
  source "$HOME/.aliasrc"
fi

### PLUGINS ###

## ZSH-Autosuggestions
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=30
if [ -f "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
  source "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi

## ZSH-Syntax-Highlighting
if [ -f "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
  source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

## ZSH-You-Should-Use
if [ -f "/usr/share/zsh/plugins/zsh-you-should-use/zsh-you-should-use.zsh" ]; then
  source "/usr/share/zsh/plugins/zsh-you-should-use/zsh-you-should-use.zsh"
fi

## ArchLinux Command Not Found
if [ -f "/usr/share/doc/pkgfile/command-not-found.zsh" ]; then
  source "/usr/share/doc/pkgfile/command-not-found.zsh"
  # else
  # function command_not_found_handler {
  #   local purple='\e[1;35m' bright='\e[0;1m' green='\e[1;32m' reset='\e[0m'
  #   printf 'zsh: command not found: %s\n' "$1"
  #   local entries=(
  #     ${(f)"$(/usr/bin/pacman -F --machinereadable -- "/usr/bin/$1")"}
  #   )
  #   if (( ${#entries[@]} ))
  #   then
  #     printf "${bright}$1${reset} may be found in the following packages:\n"
  #     local pkg
  #     for entry in "${entries[@]}"
  #     do
  #       local fields=(
  #         ${(0)entry}
  #       )
  #       if [[ "$pkg" != "${fields[2]}" ]]
  #       then
  #         printf "  ${purple}%s/${bright}%s ${green}%s${reset}\n" "${fields[1]}" "${fields[2]}" "${fields[3]}"
  #       fi
  #       printf '    /%s\n' "${fields[4]}"
  #       pkg="${fields[2]}"
  #     done
  #   fi
  #   return 127
  # }
fi

## BatPipe
eval "$(batpipe)"

## Zoxide
eval "$(zoxide init zsh)"

## FZF
if [ -f "$HOME/.fzf.zsh" ]; then
  source "$HOME/.fzf.zsh"
else
  if [ -f "/usr/share/fzf/key-bindings.zsh"]; then
    source "/usr/share/fzf/key-bindings.zsh"
  fi
  if [ -f "/usr/share/fzf/completion.zsh"]; then
    source "/usr/share/fzf/completion.zsh"
  fi
fi

## Starship prompt
eval "$(starship init zsh)"
