#!/usr/bin/env python3

####################################################
##                setupbuilder.py                 ##
##   A tool for generating dotfiles' installers   ##
##                                                ##
##                     GGORG                      ##
##          https://gh.ggorg.tk/dotfiles          ##
##             tools/setupbuilder.py              ##
####################################################

import argparse
import json
import os
from headergen import gen_nice_header


def scan_files(path: str, files: list):
    dfiles = {}
    for file in files:
        with open(os.path.join(path, file), "r") as f:
            lines = f.readlines()
        for line in lines:
            line = line.strip()
            if not line.startswith("##"):
                continue
            line = line.lstrip("## ").strip()
            if line.startswith("@Copy"):
                dfiles[file] = line.split()[1].replace("~", "$HOME")

    return dfiles


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--path", required=True,
                        help="Directory to generate a setup for")
    args = parser.parse_args()

    with open(os.path.join(args.path, "dotfiles.json"), "r") as f:
        metadata = json.load(f)

    aurdeps = [dep[4:]
               for dep in metadata["pkgdepends"] if dep.startswith("aur:")]
    pkgdeps = [dep for dep in metadata["pkgdepends"]
               if not dep.startswith("aur:")]

    files = scan_files(args.path, metadata['files'])

    setup = """#!/bin/bash

## This file has been generated by tools/setupbuilder.py

""" + \
        gen_nice_header("setup.sh", os.path.join(args.path, "setup.sh"), "A dotfile installer for ArchLinux") + "\n" + \
        f'echo -e "\\e[1;33m{metadata["name"]} \\e[1;32mdotfiles setup \\e[4;33mfor ArchLinux\\e[0m"' + \
        """
if [ -f .installed ]; then
    echo -e "\\e[1;33m[!] Already installed!\\e[0m"
    echo -e "\\e[1;33m To reinstall, remove the \\e[4;34m.installed\\e[0m\\e[1;33m file.\\e[0m"
    exit 1
fi
""" + \
        """
echo -e "\\e[1;32m[*] Installing packages...\\e[0m"

""" + \
        f"sudo pacman -Sy --needed --noconfirm {' '.join(pkgdeps)} || exit 1\n"

    if aurdeps:
        setup += """
if ! hash paru 2>/dev/null; then
    echo -e "\\e[1;32m[*] Installing \\e[1;33mparu \\e[1;32m[*]AUR helper...\\e[0m"
    git clone https://aur.archlinux.org/paru-bin.git
    cd paru-bin
    makepkg -si
    cd ..
    rm -rf paru-bin
fi

echo -e "\\e[1;32m[*] Installing AUR packages...\\e[0m"
""" + \
            f"paru -S --needed --noconfirm {' '.join(aurdeps)} || exit 1\n\n"

    setup += 'echo -e "\\e[1;32m[*] Backing up your existing dotfiles...\\e[0m"\n'

    setup += ''.join([f'''
echo -e "\\e[0;33m - {file}...\\e[0m"
mv "{file}" "{file}.bak"
''' for file in files.values()])

    setup += "\n\n"

    setup += 'echo -e "\\e[1;32m[*] Symlinking the dotfiles...\\e[0m"\n'

    setup += ''.join([f'''
echo -e "\\e[0;33m - {file}...\\e[0m"
ln -s "$PWD/{file}" "{dest}"
''' for file, dest in files.items()])

    setup += "\necho -e '\\e[1;33m[!] Do \\e[4mnot\\e[0m\\e[1;33m remove or move this repo or your dotfiles will break!\\e[0m'\n"

    if metadata["depends"]:
        setup += '\necho -e "\\e[1;32m[*] Installing dependencies...\\e[0m"\n'
        setup += "oldpwd=$PWD\n"
        setup += f'cd {len(args.path.split("/")) * "../"}'

        setup += ''.join([f'''
echo -e "\\e[0;33m - {dep}...\\e[0m"
cd {dep}
bash setup.sh
cd {len(dep.split("/")) * "../"}
''' for dep in metadata['depends']])

        setup += "cd $oldpwd\n\n"

    setup += 'echo "$PWD" > "$HOME/.dotfiles_setup_path"\n'

    setup += 'touch .installed\n'

    with open(os.path.join(args.path, "setup.sh"), "w") as f:
        f.write(setup)


if __name__ == "__main__":
    main()
