#!/bin/bash

## This file has been generated by tools/setupbuilder.py

###########################################
##                setup.sh               ##
##   A dotfile installer for ArchLinux   ##
##                                       ##
##                 GGORG                 ##
##      https://gh.ggorg.tk/dotfiles     ##
##    shells/starship-prompt/setup.sh    ##
###########################################
echo -e "\e[1;33mStarship \e[1;32mdotfiles setup \e[4;33mfor ArchLinux\e[0m"
if [ -f .installed ]; then
    echo -e "\e[1;33m[!] Already installed!\e[0m"
    echo -e "\e[1;33m To reinstall, remove the \e[4;34m.installed\e[0m\e[1;33m file.\e[0m"
    exit 1
fi

echo -e "\e[1;32m[*] Installing packages...\e[0m"

sudo pacman -Sy --needed --noconfirm starship || exit 1
echo -e "\e[1;32m[*] Backing up your existing dotfiles...\e[0m"

echo -e "\e[0;33m - $HOME/.config/starship.toml...\e[0m"
mv "$HOME/.config/starship.toml" "$HOME/.config/starship.toml.bak"


echo -e "\e[1;32m[*] Symlinking the dotfiles...\e[0m"

echo -e "\e[0;33m - starship.toml...\e[0m"
ln -s "$PWD/starship.toml" "$HOME/.config/starship.toml"

echo -e '\e[1;33m[!] Do \e[4mnot\e[0m\e[1;33m remove or move this repo or your dotfiles will break!\e[0m'
echo "$PWD" > "$HOME/.dotfiles_setup_path"
touch .installed
